sudo: false

env:
  - DOCKERFILE=Dockerfile.ubuntu DOCKERTAG=ubuntu-14.04
  - DOCKERFILE=Dockerfile.centos DOCKERTAG=centos-7

services:
  - docker

install:
  - COMMIT=${TRAVIS_COMMIT::8} ;
  - REPO=abdealijk/file-metadata ;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS ;
  - docker build -f $DOCKERFILE -t $REPO:$COMMIT . ;
  - docker tag $REPO:$COMMIT $REPO:$DOCKERTAG ;
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ;

script:
  - docker images ;
  - docker run -w /opt/file-metadata -t --rm $REPO:$COMMIT python -m pytest ;
  # Upload to docker if it's on the master branch
  # - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
  #     docker push $REPO ;
  #   fi

notifications:
  email: false
