sudo: false

services:
  - docker

install:
  - COMMIT=${TRAVIS_COMMIT::8} ;
  - REPO=abdealijk/file-metadata ;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS ;
  - docker build -f Dockerfile -t $REPO:$COMMIT . ;
  - docker tag $REPO:$COMMIT $REPO:latest ;
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ;

script:
  - docker images ;
  # Upload to docker if it's on the master branch
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
      docker push $REPO ;
    fi

notifications:
  email: false
